# Site settings
author: Natasha Chernis
title: Coding with 4GB of RAM
header-img: img/home-bg.png
email: natashachernis@gmail.com
copyright_name: Natasha Chernis
description: > # this means to ignore newlines until "baseurl:"
  The chronicles of a Texan learning to code on an ancient MacBook Air
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  iamtash

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
